### ISSUE TITLE
Porting Mac native library to Maui

### ISSUE THREAD

**Issue by 420tech** [realZhangChi/MauiBinding#3]
Will your tool help with that?

**Comment by realZhangChi** [comment]
Hi, @420tech 
Which Mac native library are you going to use? Creating a Mac Catalyst binding library may require a macbook, but I don't have one at the moment. You can tell me which Mac native library you need to use, I will create the Mac binding class library when I have a MacBook.

**Comment by 420tech** [comment]
It is our own sound controller. We are migrating everything to Maui and we made this library our native Mac app.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by realZhangChi** [comment]
I'm sorry that this project may not be of much help, you can use the `dotnet new maccatalystbinding` command to create a Mac OS binding class library for Maui, and refer to the [xamarin documentation](https://learn.microsoft.com/en-us/xamarin/cross-platform/macios/binding/?context=xamarin%2Fmac) to bind your native library.

**Comment by 420tech** [comment]
Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
