### ISSUE TITLE
除了移动端，可以同时兼容windows平台和Mac平台的应用么

### ISSUE THREAD

**Issue by JaneConan** [realZhangChi/MauiBinding#4]

**Comment by realZhangChi** [comment]
这个项目只创建绑定类库，不涉及跨平台兼容逻辑。Maui的Windows平台是基于WinUI的，应该不需要创建绑定类库，对于Mac平台，目前我没有Mac笔记本，你可以提供你需要的Mac本地库，等我有了Mac笔记本就可以创建Mac绑定类库。

**Comment by JaneConan** [comment]
好的 谢谢
