### ISSUE TITLE
想使用maui开发app 使用微信openSDK 大佬能不能写个简单使用说明或者demo吗

### ISSUE THREAD

**Issue by lkd3063601** [realZhangChi/MauiBinding#8]
想用但这块不熟悉，如果能把微信和支付宝的sdk集成后用 maui Blazor Hybrid 来开发app  Blazor调用本机的微信和支付宝的sdk 那开发app就好简单了，大佬这包引用后怎么用呢，还是自己太菜了 不知道咋用，国内这块资料也太少了

**Comment by lkd3063601** [comment]
自己用大佬你这个绑定库试了下 能调用成功了，感谢，非常棒

**Comment by realZhangChi** [comment]
感谢你的支持。微信绑定库的使用，主要还是参考官方原生文档，按照原生的方式在 Maui 项目的相应位置进行开发即可。你可以参考我的另一个项目，![Booster](https://github.com/realZhangChi/Booster/tree/main/src/WeChat)，在这个项目中我尝试对微信进行封装，可以看一下这里的代码，不过这个项目已经不再维护了。

**Comment by lkd3063601** [comment]
好的 多谢
